/**
 * GENERATED by `xanosdk routes --emit`. Do not edit.
 *
 * Plain data plus one interpolator, and the request input types of every
 * endpoint, channel and message. The core sections import nothing; the only
 * imports are the packages an installed module's block declares, never the
 * SDK itself. So a frontend gets the typed path/verb (and socket) contract
 * without pulling the SDK runtime into its bundle. Regenerate after changing an
 * endpoint's name, verb, api group or inputs, or a realtime server's, channel's
 * or message's name or inputs.
 */

/**
 * An own key only. Every lookup here is keyed by a caller's string, and a plain
 * object answers `toString`, `constructor` or `hasOwnProperty` from its
 * prototype — a name no route, channel or param carries would read as one.
 */
function own<T>(record: Record<string, T>, key: string): T | undefined {
  return Object.prototype.hasOwnProperty.call(record, key) ? record[key] : undefined;
}

function fillParams(
  label: string,
  noun: string,
  template: string,
  params?: Record<string, string | number>,
  encode = false,
): string {
  const declared = [...template.matchAll(/\{([^/{}]+)\}/g)].map((m) => m[1]!);
  for (const key of Object.keys(params ?? {})) {
    if (!declared.includes(key)) {
      throw new Error(
        `${label}: \`${key}\` is not a {param} of this ${noun}.` +
          (declared.length ? ` Expected: ${declared.join(", ")}.` : ` This ${noun} is static.`),
      );
    }
  }
  const raw: Record<string, string> = {};
  const filled = template.replace(/\{([^/{}]+)\}/g, (_all, key: string) => {
    const value = own(params ?? {}, key);
    if (value === undefined || value === null || value === "") {
      throw new Error(`${label}: missing a value for the path param \`${key}\`.`);
    }
    if (typeof value === "number" && !Number.isFinite(value)) {
      throw new Error(`${label}: the path param \`${key}\` is ${value}.`);
    }
    const text = String(value);
    if (text.includes("/")) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot contain "/" — ` +
          `it would address a different ${noun}.`,
      );
    }
    if (!encode) {
      if (!/^[A-Za-z0-9_-]+$/.test(text)) {
        throw new Error(
          `${label}: the path param \`${key}\` is "${text}" — a ${noun} segment holds only ` +
            `letters, digits, "_" and "-".`,
        );
      }
      return text;
    }
    raw[key] = encodeURIComponent(text);
    return raw[key];
  });
  // A "." or ".." SEGMENT is REMOVED before routing (and takes the segment
  // before it), and the URL standard reads "%2e" as a dot for that check too.
  // Judged on the segment as sent, values encoded.
  if (encode) {
    for (const segment of template.split("/")) {
      if (!segment.includes("{")) continue;
      const assembled = segment.replace(/\{([^/{}]+)\}/g, (_all, key: string) => raw[key] ?? "");
      if (/^(\.|%2e){1,2}$/i.test(assembled)) {
        throw new Error(
          `${label}: the path segment "${segment}" cannot be "${assembled}" — ` +
            `a "." or ".." segment addresses a different ${noun}.`,
        );
      }
    }
  }
  return filled;
}

export const ROUTES = {
  "GET agent/activity": { verb: "GET", path: "/api:agent/agent/activity" },
  "GET agent/connections": { verb: "GET", path: "/api:agent/agent/connections" },
  "POST agent/connections": { verb: "POST", path: "/api:agent/agent/connections" },
  "POST agent/connections/{id}/revoke": { verb: "POST", path: "/api:agent/agent/connections/{id}/revoke" },
  "GET agent/info": { verb: "GET", path: "/api:agent/agent/info" },
  "GET app/activity": { verb: "GET", path: "/api:app/app/activity" },
  "GET app/notifications": { verb: "GET", path: "/api:app/app/notifications" },
  "POST app/notifications/{id}/read": { verb: "POST", path: "/api:app/app/notifications/{id}/read" },
  "POST app/notifications/read-all": { verb: "POST", path: "/api:app/app/notifications/read-all" },
  "GET app/notifications/unread": { verb: "GET", path: "/api:app/app/notifications/unread" },
  "GET app/people": { verb: "GET", path: "/api:app/app/people" },
  "GET app/settings": { verb: "GET", path: "/api:app/app/settings" },
  "PATCH app/settings": { verb: "PATCH", path: "/api:app/app/settings" },
  "GET approvals": { verb: "GET", path: "/api:approvals/approvals" },
  "POST approvals/{id}/approve": { verb: "POST", path: "/api:approvals/approvals/{id}/approve" },
  "POST approvals/{id}/decline": { verb: "POST", path: "/api:approvals/approvals/{id}/decline" },
  "POST auth/demo": { verb: "POST", path: "/api:authn/auth/demo" },
  "GET auth/demo/personas": { verb: "GET", path: "/api:authn/auth/demo/personas" },
  "GET auth/invites": { verb: "GET", path: "/api:authn/auth/invites" },
  "POST auth/invites": { verb: "POST", path: "/api:authn/auth/invites" },
  "POST auth/invites/{id}/revoke": { verb: "POST", path: "/api:authn/auth/invites/{id}/revoke" },
  "POST auth/link": { verb: "POST", path: "/api:authn/auth/link" },
  "POST auth/link/accept": { verb: "POST", path: "/api:authn/auth/link/accept" },
  "POST auth/login": { verb: "POST", path: "/api:authn/auth/login" },
  "GET auth/me": { verb: "GET", path: "/api:authn/auth/me" },
  "PATCH auth/me": { verb: "PATCH", path: "/api:authn/auth/me" },
  "POST auth/me/password": { verb: "POST", path: "/api:authn/auth/me/password" },
  "POST auth/people/{id}/reset-link": { verb: "POST", path: "/api:authn/auth/people/{id}/reset-link" },
  "POST auth/signup": { verb: "POST", path: "/api:authn/auth/signup" },
  "GET chat/conversations": { verb: "GET", path: "/api:chat/chat/conversations" },
  "DELETE chat/conversations/{conversation_id}": { verb: "DELETE", path: "/api:chat/chat/conversations/{conversation_id}" },
  "GET chat/conversations/{conversation_id}/messages": { verb: "GET", path: "/api:chat/chat/conversations/{conversation_id}/messages" },
  "POST chat/conversations/{conversation_id}/send": { verb: "POST", path: "/api:chat/chat/conversations/{conversation_id}/send" },
  "POST chat/conversations/create": { verb: "POST", path: "/api:chat/chat/conversations/create" },
  "POST mcp_oauth/complete": { verb: "POST", path: "/api:mcp-oauth-vendor-onboarding-review/mcp_oauth/complete" },
  "GET mcp_oauth/login": { verb: "GET", path: "/api:mcp-oauth-vendor-onboarding-review/mcp_oauth/login" },
  "GET mcp_oauth/request": { verb: "GET", path: "/api:mcp-oauth-vendor-onboarding-review/mcp_oauth/request" },
  "POST mcp_oauth/sign_in": { verb: "POST", path: "/api:mcp-oauth-vendor-onboarding-review/mcp_oauth/sign_in" },
  "GET overview": { verb: "GET", path: "/api:onboarding/overview" },
  "GET queue": { verb: "GET", path: "/api:onboarding/queue" },
  "GET rules": { verb: "GET", path: "/api:onboarding/rules" },
  "POST rules/activate": { verb: "POST", path: "/api:onboarding/rules/activate" },
  "PATCH settings": { verb: "PATCH", path: "/api:onboarding/settings" },
  "POST submissions": { verb: "POST", path: "/api:onboarding/submissions" },
  "GET submissions/{id}": { verb: "GET", path: "/api:onboarding/submissions/{id}" },
  "POST submissions/{id}/approvals/{approval_id}/approve": { verb: "POST", path: "/api:onboarding/submissions/{id}/approvals/{approval_id}/approve" },
  "POST submissions/{id}/approvals/{approval_id}/reject": { verb: "POST", path: "/api:onboarding/submissions/{id}/approvals/{approval_id}/reject" },
  "POST submissions/{id}/complete": { verb: "POST", path: "/api:onboarding/submissions/{id}/complete" },
  "POST submissions/{id}/rescore": { verb: "POST", path: "/api:onboarding/submissions/{id}/rescore" },
  "GET submissions/mine": { verb: "GET", path: "/api:onboarding/submissions/mine" },
  "GET vendors": { verb: "GET", path: "/api:onboarding/vendors" },
  "GET rbac/changes": { verb: "GET", path: "/api:rbac/rbac/changes" },
  "GET rbac/me": { verb: "GET", path: "/api:rbac/rbac/me" },
  "GET rbac/members": { verb: "GET", path: "/api:rbac/rbac/members" },
  "POST rbac/members/{id}/role": { verb: "POST", path: "/api:rbac/rbac/members/{id}/role" },
} as const;

/**
 * Every endpoint in this workspace, keyed `"<VERB> <name>"` (e.g. `"GET listings"`),
 * or `"<group>:<VERB> <name>"` when that pair is in more than one api group.
 */
export type RouteName = keyof typeof ROUTES;

/** `N` when it is a union of two or more route names, else `never`. */
type ManyRoutes<N> = [(N extends unknown ? (x: N) => void : never) extends (x: infer I) => void ? I : never] extends [never] ? N : never;

/** A union of route names (e.g. a `key: RouteName` parameter): params checked at runtime. */
export function routePath<N extends RouteName>(name: ManyRoutes<N>, params?: Record<string, string | number>): string;
export function routePath(name: "GET agent/activity"): string;
export function routePath(name: "GET agent/connections"): string;
export function routePath(name: "POST agent/connections"): string;
export function routePath(name: "POST agent/connections/{id}/revoke", params: { "id": string | number }): string;
export function routePath(name: "GET agent/info"): string;
export function routePath(name: "GET app/activity"): string;
export function routePath(name: "GET app/notifications"): string;
export function routePath(name: "POST app/notifications/{id}/read", params: { "id": string | number }): string;
export function routePath(name: "POST app/notifications/read-all"): string;
export function routePath(name: "GET app/notifications/unread"): string;
export function routePath(name: "GET app/people"): string;
export function routePath(name: "GET app/settings"): string;
export function routePath(name: "PATCH app/settings"): string;
export function routePath(name: "GET approvals"): string;
export function routePath(name: "POST approvals/{id}/approve", params: { "id": string | number }): string;
export function routePath(name: "POST approvals/{id}/decline", params: { "id": string | number }): string;
export function routePath(name: "POST auth/demo"): string;
export function routePath(name: "GET auth/demo/personas"): string;
export function routePath(name: "GET auth/invites"): string;
export function routePath(name: "POST auth/invites"): string;
export function routePath(name: "POST auth/invites/{id}/revoke", params: { "id": string | number }): string;
export function routePath(name: "POST auth/link"): string;
export function routePath(name: "POST auth/link/accept"): string;
export function routePath(name: "POST auth/login"): string;
export function routePath(name: "GET auth/me"): string;
export function routePath(name: "PATCH auth/me"): string;
export function routePath(name: "POST auth/me/password"): string;
export function routePath(name: "POST auth/people/{id}/reset-link", params: { "id": string | number }): string;
export function routePath(name: "POST auth/signup"): string;
export function routePath(name: "GET chat/conversations"): string;
export function routePath(name: "DELETE chat/conversations/{conversation_id}", params: { "conversation_id": string | number }): string;
export function routePath(name: "GET chat/conversations/{conversation_id}/messages", params: { "conversation_id": string | number }): string;
export function routePath(name: "POST chat/conversations/{conversation_id}/send", params: { "conversation_id": string | number }): string;
export function routePath(name: "POST chat/conversations/create"): string;
export function routePath(name: "POST mcp_oauth/complete"): string;
export function routePath(name: "GET mcp_oauth/login"): string;
export function routePath(name: "GET mcp_oauth/request"): string;
export function routePath(name: "POST mcp_oauth/sign_in"): string;
export function routePath(name: "GET overview"): string;
export function routePath(name: "GET queue"): string;
export function routePath(name: "GET rules"): string;
export function routePath(name: "POST rules/activate"): string;
export function routePath(name: "PATCH settings"): string;
export function routePath(name: "POST submissions"): string;
export function routePath(name: "GET submissions/{id}", params: { "id": string | number }): string;
export function routePath(name: "POST submissions/{id}/approvals/{approval_id}/approve", params: { "id": string | number; "approval_id": string | number }): string;
export function routePath(name: "POST submissions/{id}/approvals/{approval_id}/reject", params: { "id": string | number; "approval_id": string | number }): string;
export function routePath(name: "POST submissions/{id}/complete", params: { "id": string | number }): string;
export function routePath(name: "POST submissions/{id}/rescore", params: { "id": string | number }): string;
export function routePath(name: "GET submissions/mine"): string;
export function routePath(name: "GET vendors"): string;
export function routePath(name: "GET rbac/changes"): string;
export function routePath(name: "GET rbac/me"): string;
export function routePath(name: "GET rbac/members"): string;
export function routePath(name: "POST rbac/members/{id}/role", params: { "id": string | number }): string;

export function routePath(name: RouteName, params?: Record<string, string | number>): string {
  // Read through a widened view: a workspace with no endpoints at all makes
  // `RouteName` `never`, which cannot index the literal type.
  const route = own(ROUTES as Record<string, { verb: string; path: string }>, name);
  if (!route) {
    throw new Error(
      `routePath: unknown route "${String(name)}". Routes are keyed "<VERB> <name>", ` +
        'e.g. "GET listings" — regenerate the manifest if the endpoint is new.',
    );
  }
  return fillParams(`routePath("${String(name)}")`, "route", route.path, params, true);
}

/** Every realtime server in this workspace, by name, with its resolved canonical. */
export const REALTIME_SERVERS = {
  "live": { canonical: "live" },
} as const;

/** Every realtime server name in this workspace. */
export type RealtimeServerName = keyof typeof REALTIME_SERVERS;

/** Every realtime channel in this workspace, by path, with its owning server. */
export const CHANNELS = {
  "app": { server: "live" },
  "rooms/{room}": { server: "live" },
  "users/{user_id}": { server: "live" },
} as const;

/** Every realtime channel path in this workspace. */
export type ChannelName = keyof typeof CHANNELS;

export function channelPath(name: "app"): string;
export function channelPath(name: "rooms/{room}", params: { "room": string | number }): string;
export function channelPath(name: "users/{user_id}", params: { "user_id": string | number }): string;

export function channelPath(name: ChannelName, params?: Record<string, string | number>): string {
  if (!own(CHANNELS as Record<string, unknown>, name)) {
    throw new Error(`channelPath: unknown channel "${String(name)}".`);
  }
  return fillParams(`channelPath("${String(name)}")`, "channel", String(name), params);
}

/** Reject a tenant name that would break the \`<tenant>:<canonical>\` split. */
function assertTenant(tenant: string): string {
  if (!/^[A-Za-z0-9-]+$/.test(tenant)) {
    throw new Error(
      `socketUrl: invalid \`tenant\` ${JSON.stringify(tenant)} — a tenant name is alphanumeric with ` +
        `dashes (e.g. "xxxx-xxxx-xxxx"). It rides as a "<tenant>:<canonical>" prefix, so ":" and "/" ` +
        "cannot appear in it.",
    );
  }
  return tenant;
}

/** The websocket PATH — \`/ws/<canonical>\`, or \`/ws/<tenant>:<canonical>\`. */
export function socketPath(server: RealtimeServerName, opts?: { tenant?: string | undefined }): string {
  const entry = own(REALTIME_SERVERS as Record<string, { canonical: string }>, server);
  if (!entry) throw new Error(`socketPath: unknown realtime server "${String(server)}".`);
  const prefix = opts?.tenant ? `${assertTenant(opts.tenant)}:` : "";
  return `/ws/${prefix}${entry.canonical}`;
}

/** The absolute websocket URL — \`baseUrl\` + {@link socketPath}, scheme normalized to ws/wss. */
export function socketUrl(
  server: RealtimeServerName,
  baseUrl: string,
  opts?: { tenant?: string | undefined },
): string {
  if (!own(REALTIME_SERVERS as Record<string, unknown>, server)) {
    throw new Error(`socketUrl: unknown realtime server "${String(server)}".`);
  }
  const base = (baseUrl ?? "").trim().replace(/\/+$/, "");
  if (!base) throw new Error('socketUrl: needs a base URL (e.g. "https://x.dev.xano.io").');
  const socketBase = /^wss?:\/\//i.test(base)
    ? base
    : /^https?:\/\//i.test(base)
      ? base.replace(/^http/i, "ws")
      : `wss://${base}`;
  // A base URL ending in \`/ws/<something>\` is this function's own output fed back
  // in. Appending a second \`/ws/<canonical>\` is wrong twice: the extra segments
  // join the connection hash, and the tenant is dropped (the first call already
  // consumed the \`/tenant/<name>\` prefix). Refuse rather than dial a bad URL.
  if (/\/ws\/[^/]+$/i.test(socketBase)) {
    throw new Error(
      `socketUrl: \`baseUrl\` already carries a socket path (${base}). Pass the http(s) ` +
        "INSTANCE base URL, not the result of a previous socketUrl()/getUrl() — resolving twice " +
        'appends a second "/ws/<canonical>" and drops the tenant.',
    );
  }
  // A query, a fragment or an API group's \`/api:<…>\` path is not an instance
  // base: the socket path appended after it never reaches the server.
  if (/[?#]/.test(base) || /\/api:/i.test(base)) {
    throw new Error(
      `socketUrl: \`baseUrl\` is not an instance base URL (${base}). Pass "https://<host>" or ` +
        '"https://<host>/tenant/<name>" — no query, fragment or /api:<…> path.',
    );
  }
  // A tenant base URL names its tenant as its own path segment; the socket glues
  // it to the canonical inside one segment. Translate rather than concatenate —
  // the concatenated form never upgrades at all.
  const lifted = /^(wss?:\/\/[^/]+)\/tenant\/([^/]+)(\/.*)?$/i.exec(socketBase);
  let origin = socketBase;
  let tenant = opts?.tenant;
  if (lifted) {
    const fromBase = lifted[2]!;
    if (tenant !== undefined && tenant !== fromBase) {
      throw new Error(
        `socketUrl: given tenant ${JSON.stringify(tenant)} but the base URL names ` +
          `${JSON.stringify(fromBase)} (".../tenant/${fromBase}"). Refusing to guess which one you ` +
          "meant — pass the matching tenant, or a base URL without the \"/tenant/<name>\" prefix.",
      );
    }
    origin = `${lifted[1]!}${lifted[3] ?? ""}`;
    tenant = assertTenant(fromBase);
  }
  return `${origin}${socketPath(server, { tenant })}`;
}

/**
 * The request body/query inputs of every endpoint, keyed exactly like ROUTES.
 * Path params are inputs too, so they appear here as well as in routePath().
 * Matches InferInput<typeof def>, except that a database-link input appears as
 * the linked table's columns, which is what the server accepts.
 */
export type RouteInputs = {
  "GET agent/activity": {};
  "GET agent/connections": {};
  "POST agent/connections": {
    name: string;
    scope: "read" | "read_write";
    days: number;
  };
  "POST agent/connections/{id}/revoke": {
    id: number;
  };
  "GET agent/info": {};
  "GET app/activity": {
    entity?: string;
    entity_id?: number;
    page?: number;
    per_page?: number;
  };
  "GET app/notifications": {
    unread?: boolean;
    page?: number;
  };
  "POST app/notifications/{id}/read": {
    id: number;
  };
  "POST app/notifications/read-all": {};
  "GET app/notifications/unread": {};
  "GET app/people": {};
  "GET app/settings": {};
  "PATCH app/settings": {
    name: string;
    timezone?: string;
    week_start?: "monday" | "sunday";
  };
  "GET approvals": {
    view?: "pending" | "decided";
    page?: number;
  };
  "POST approvals/{id}/approve": {
    id: number;
    edited?: string;
  };
  "POST approvals/{id}/decline": {
    id: number;
  };
  "POST auth/demo": {
    persona: string;
  };
  "GET auth/demo/personas": {};
  "GET auth/invites": {};
  "POST auth/invites": {
    email: string;
    name?: string;
    role: "admin" | "approver" | "requester";
  };
  "POST auth/invites/{id}/revoke": {
    id: number;
  };
  "POST auth/link": {
    token: string;
  };
  "POST auth/link/accept": {
    token: string;
    name?: string;
    password: string;
  };
  "POST auth/login": {
    email?: string;
    password?: string;
  };
  "GET auth/me": {};
  "PATCH auth/me": {
    name: string;
  };
  "POST auth/me/password": {
    current_password: string;
    new_password: string;
  };
  "POST auth/people/{id}/reset-link": {
    id: number;
  };
  "POST auth/signup": {
    name?: string;
    email?: string;
    password?: string;
  };
  "GET chat/conversations": {};
  "DELETE chat/conversations/{conversation_id}": {
    conversation_id: number;
  };
  "GET chat/conversations/{conversation_id}/messages": {
    conversation_id: number;
  };
  "POST chat/conversations/{conversation_id}/send": {
    conversation_id: number;
    content?: string;
    message?: string;
    prompt?: string;
  };
  "POST chat/conversations/create": {
    title?: string;
  };
  "POST mcp_oauth/complete": {
    mcp_request: string;
    decision: "approve" | "deny";
  };
  "GET mcp_oauth/login": {
    mcp_request?: string;
  };
  "GET mcp_oauth/request": {
    mcp_request: string;
  };
  "POST mcp_oauth/sign_in": {
    email: string;
    password: string;
  };
  "GET overview": {};
  "GET queue": {
    status?: string;
    risk_tier?: string;
    page?: number;
    per_page?: number;
  };
  "GET rules": {};
  "POST rules/activate": {};
  "PATCH settings": {
    review_sla_days: number;
  };
  "POST submissions": {
    vendor_id?: number;
    name?: string;
    category?: "software" | "hardware" | "services" | "data_processor";
    country?: string;
    annual_spend_band?: "low" | "mid" | "high";
    data_access_level?: "none" | "internal" | "pii";
  };
  "GET submissions/{id}": {
    id: number;
  };
  "POST submissions/{id}/approvals/{approval_id}/approve": {
    id: number;
    approval_id: number;
  };
  "POST submissions/{id}/approvals/{approval_id}/reject": {
    id: number;
    approval_id: number;
    reason: string;
  };
  "POST submissions/{id}/complete": {
    id: number;
  };
  "POST submissions/{id}/rescore": {
    id: number;
  };
  "GET submissions/mine": {
    status?: string;
    page?: number;
    per_page?: number;
  };
  "GET vendors": {
    category?: string;
    data_access_level?: string;
    page?: number;
    per_page?: number;
  };
  "GET rbac/changes": {};
  "GET rbac/me": {};
  "GET rbac/members": {
    q?: string;
    page?: number;
  };
  "POST rbac/members/{id}/role": {
    id: number;
    role: "admin" | "approver" | "requester";
  };
};

/** The path params of every realtime channel, keyed exactly like CHANNELS. */
export type ChannelInputs = {
  "app": {};
  "rooms/{room}": {
    room?: string;
  };
  "users/{user_id}": {
    user_id?: number;
  };
};

/**
 * The payload of every realtime message, keyed "<channel key> <message name>"
 * (e.g. "rooms/{room_id} send").
 */
export type MessageInputs = {};

/** Every realtime message in this workspace, keyed "<channel key> <message name>". */
export type MessageName = keyof MessageInputs;
